language: go
go:
  - tip
os:
  - linux
before_install:
  - sudo apt-get update
  - sudo apt-get install python-virtualenv
  - pip install --upgrade pip setuptools
install:
  - make depends
  - make 
script: make test
notifications:
  email: false