language: python
python:
  - "2.7"
os:
  - linux
before_install:
  - sudo apt-get update
  - sudo apt-get install -y golang
  - pip install cwltool
install:
  - make depends
  - make 
  - git clone https://github.com/common-workflow-language/common-workflow-language.git
script: cd common-workflow-language && ./run_test.sh RUNNER=../bin/cwlgo-tool common-workflow-language/v1.0/
notifications:
  email: false